import 'package:interview2/pet_model.dart';

List<Pet> petList = [
  Pet('Dog', 'Golden', 20,
      'https://drive.usercontent.google.com/download?id=1SVXNgYjWidATdPpPfswlWtS31DnhjB-2'),
  Pet('Lablador', 'Dog', 18,
      'https://drive.usercontent.google.com/download?id=152WsHjSIgQUy0gS_WQEo3mWOSMK8v1kM'),
  Pet('Dog', 'Cardigan', 12,
      'https://drive.usercontent.google.com/download?id=1fHoNz-wywIk_ta4RIJzXm7yLrObyKDty'),
  Pet('Cat', 'Street Cat', 17,
      'https://drive.usercontent.google.com/download?id=1SL7ZirhhuTpgk7wRe_t0vB_3xD9iqCGm'),
  Pet('Cat', 'White Cat', 19,
      'https://drive.usercontent.google.com/download?id=1C_S4qQ4wck3LasJ1Bs5Lz8yhwN60SmTH'),
  Pet('Cat', 'Kitten', 18,
      'https://drive.usercontent.google.com/download?id=1qQILdlJ3gtm_0VBzmSoqgTbisVZ-7kr9'),
  Pet('Bird', 'House Bird', 1,
      'https://drive.usercontent.google.com/download?id=1LbUWy1JxxkSGSd4cu4dMBK5ChilbFud8'),
  Pet('Bird', 'Parrot', 14,
      'https://drive.usercontent.google.com/download?id=1B9eAFq_9D75eXtn0BJM6gtq811eby6QN'),
  Pet('Bird', 'Pink Bird', 15,
      'https://drive.usercontent.google.com/download?id=1Sg8plSKxYt1kRQn_DH_OdvHiE2FoeQah'),
  Pet('Bird', 'Talking Parrot', 17,
      'https://drive.usercontent.google.com/download?id=1Sg8plSKxYt1kRQn_DH_OdvHiE2FoeQah'),
  Pet('Rat', 'Hamster', 9,
      'https://drive.usercontent.google.com/download?id=11tVuPyyv23mByiFNHrJRuE55gyhMrGA2'),
  Pet('Rabbit', 'Brown Rabbit', 16,
      'https://drive.usercontent.google.com/download?id=1huzYq6qlL4BiFzXqD7SuMYM67J5Ea0bV'),
  Pet('Rabbit', 'Gray Rabbit', 17,
      'https://drive.usercontent.google.com/download?id=1lxI-yXMPIp2nz2MLc7duJ5Sw6lrA-AsJ'),
];
